"""Validation driver for the neXtProt schema re-import script.

The region is a whole script: it reads "schema.ttl" and three Google-Doc
exports (TSV) from the current directory, hides the entities marked Private,
rewrites the rdfs:label / rdfs:comment of the others, and serialises the graph
after each file ("schema-tmp.N") and at the end ("schema-new.ttl").

schema.ttl is generated by the neXtProt build and is not in the repository, so
the driver stages a working directory from the fixtures next to this file:
fixture.ttl becomes schema.ttl, and goofiles_fixture/ holds the three TSV files
under their exact names (rows copied verbatim from the repository).  Both
versions run there, so nothing is written back into the example directory.

Oracle: module state — the `g` global of both runs by RDF isomorphism, plus
the captured stdout, which the script uses heavily (triple counts after each
removal step, "### Unknown uri", the label/comment change log).
"""
import os
import shutil
import tempfile
from pathlib import Path

from rdfeval.harness import run_pair

HERE = Path(__file__).resolve().parent

work = Path(tempfile.mkdtemp(prefix="nextprot-reimport-"))
shutil.copy(HERE / "fixture.ttl", work / "schema.ttl")
for tsv in (HERE / "goofiles_fixture").iterdir():
    shutil.copy(tsv, work / tsv.name)
os.chdir(work)

VERDICT = run_pair(str(HERE / "driver.py"), entry=None, calls=None)

os.chdir(HERE)
shutil.rmtree(work, ignore_errors=True)
