# Context shim (see meta.json), for
# ktbs/ktbs@4f9f50c770cde629c5a75a2d3f502503738bdaf0.
#
# The region imports two things this checkout cannot resolve standalone:
#
#  1. `rdfrest` is not an installed package (only vendored inside the ktbs
#     monorepo, lib/rdfrest/), so `from rdfrest.util... import ...` fails.
#     ISO8601_REGEX/TIMEZONE_REGEX/ParseError/Utc/UTC/FixedOffset/
#     parse_timezone/parse_date are copied VERBATIM from
#     lib/rdfrest/util/iso8601.py; cache_result/coerce_to_uri/coerce_to_node
#     VERBATIM from lib/rdfrest/util/__init__.py (functions unused by this
#     region -- check_new, extsplit, make_fresh_uri -- are not carried over).
#
#  2. `from ..namespace import KTBS` and `from .obsel import ObselMixin,
#     ObselProxy` are package-relative imports that only resolve inside the
#     ktbs package; the region runs standalone here. KTBS is the real
#     project namespace IRI from lib/ktbs/namespace.py
#     (http://liris.cnrs.fr/silex/2009/ktbs#), reduced from ClosedNamespace
#     (which asserts membership against a large generated identifier set)
#     to a plain rdflib Namespace -- same simplification used by other
#     context shims in this study. ObselMixin/ObselProxy below are empty
#     placeholders, present only so the module-level import succeeds: the
#     driver's demo() harness always calls create_obsel with
#     no_return=True (see meta.json), so the `self.factory(...)` /
#     `isinstance(ret, ObselMixin)` branch that is their only use in the
#     region is never reached, and no behaviour of theirs is exercised.
#
# _TraceStub below is NOT from the project. StoredTraceMixin.create_obsel's
# job is to BUILD a graph and hand it to `self.post_graph(...)` -- the
# REST/storage layer that receives it is out of scope for a region under
# study for its graph construction. _TraceStub stands in for `self`,
# providing only the two members the region actually touches
# (get_default_subject, post_graph) plus the obsel_collection.
# force_state_refresh() no-op called unconditionally before the
# no_return check. It invents no RDF-producing logic -- it only captures,
# unchanged, the graph the region already built.

import re
from datetime import datetime, timedelta, tzinfo
from functools import wraps

from rdflib import BNode, Graph, Namespace, URIRef

# --- lib/ktbs/namespace.py (trimmed: ClosedNamespace -> Namespace) --------

KTBS = Namespace("http://liris.cnrs.fr/silex/2009/ktbs#")

# ldpy's prefix-import protocol (`from context_shim import ktbs:`, see
# reference/language/declarations.md "Prefixes across modules") reads this
# dict off the imported module -- normally auto-generated by the transpiler
# for an .ldpy module that declares `@prefix ktbs: <...> .` at module level;
# this is a plain .py shim, so it is provided by hand, to the same shape.
__namespaces__ = {"ktbs": KTBS}


# --- lib/rdfrest/util/iso8601.py (verbatim) --------------------------------

ISO8601_REGEX = re.compile(
    r"(?P<year>[0-9]{4})(-(?P<month>[0-9]{1,2})(-(?P<day>[0-9]{1,2})"
    r"((?P<separator>.)(?P<hour>[0-9]{2}):(?P<minute>[0-9]{2})(:(?P<second>[0-9]{2})(\.(?P<fraction>[0-9]+))?)?"
    r"(?P<timezone>Z|(([-+])([0-9]{2}):([0-9]{2})))?)?)?)?"
)
TIMEZONE_REGEX = re.compile("(?P<prefix>[+-])(?P<hours>[0-9]{2}).(?P<minutes>[0-9]{2})")


class ParseError(Exception):
    """Raised when there is a problem parsing a date string"""


ZERO = timedelta(0)


class Utc(tzinfo):
    def utcoffset(self, dt):
        return ZERO

    def tzname(self, dt):
        return "UTC"

    def dst(self, dt):
        return ZERO


UTC = Utc()


class FixedOffset(tzinfo):
    def __init__(self, offset_hours, offset_minutes, name):
        self.__offset = timedelta(hours=offset_hours, minutes=offset_minutes)
        self.__name = name

    def utcoffset(self, dt):
        return self.__offset

    def tzname(self, dt):
        return self.__name

    def dst(self, dt):
        return ZERO

    def __repr__(self):
        return "<FixedOffset %r>" % self.__name


def parse_timezone(tzstring, default_timezone=UTC):
    if tzstring == "Z":
        return default_timezone
    if tzstring is None:
        return default_timezone
    m = TIMEZONE_REGEX.match(tzstring)
    prefix, hours, minutes = m.groups()
    hours, minutes = int(hours), int(minutes)
    if prefix == "-":
        hours = -hours
        minutes = -minutes
    return FixedOffset(hours, minutes, tzstring)


def parse_date(datestring, default_timezone=UTC):
    if not isinstance(datestring, str):
        raise ParseError("Expecting a string %r" % datestring)
    m = ISO8601_REGEX.match(datestring)
    if not m:
        raise ParseError("Unable to parse date string %r" % datestring)
    groups = m.groupdict()
    tz = parse_timezone(groups["timezone"], default_timezone=default_timezone)
    if groups["fraction"] is None:
        groups["fraction"] = 0
    else:
        groups["fraction"] = int(float("0.%s" % groups["fraction"]) * 1e6)
    return datetime(
        int(groups["year"]),
        int(groups["month"] or 1),
        int(groups["day"] or 1),
        int(groups["hour"] or 0),
        int(groups["minute"] or 0),
        int(groups["second"] or 0),
        int(groups["fraction"] or 0),
        tz,
    )


# --- lib/rdfrest/util/__init__.py (verbatim) -------------------------------

def cache_result(callabl):
    """Decorator for caching the result of a callable."""
    cache_name = "__cache_%s" % callabl.__name__

    @wraps(callabl)
    def wrapper(self):
        if cache_name not in self.__dict__:
            ret = callabl(self)
            setattr(self, cache_name, ret)
        else:
            ret = getattr(self, cache_name)
        return ret

    return wrapper


def coerce_to_uri(obj, base=None):
    """I convert `obj` to a URIRef."""
    assert obj is not None
    ret = obj
    if not isinstance(ret, URIRef):
        ret = getattr(ret, "uri", None) or str(ret)
    if not isinstance(ret, URIRef):
        ret = URIRef(ret, base)
    return ret


def coerce_to_node(obj, base=None):
    """Like coerce_to_uri, but None -> fresh BNode, BNode -> itself."""
    if obj is None:
        return BNode()
    elif isinstance(obj, BNode):
        return obj
    else:
        return coerce_to_uri(obj, base)


# --- lib/ktbs/api/obsel.py (placeholders, see module docstring) -----------

class ObselMixin:
    pass


class ObselProxy:
    pass


# --- demo harness support (not from the project) ---------------------------

class _TraceStub:
    """Stands in for the StoredTrace `self` -- see module docstring."""

    def __init__(self, uri="http://example.org/base/t1/",
                 default_subject="http://example.org/base/default-subject"):
        self.uri = URIRef(uri)
        self._default_subject = URIRef(default_subject)
        self.captured_graph = None
        self.obsel_collection = self

    def get_default_subject(self):
        return self._default_subject

    def post_graph(self, graph, _parameters, _trust, obs_uri, _obsel_type):
        self.captured_graph = Graph()
        for triple in graph:
            self.captured_graph.add(triple)
        return [obs_uri]

    def force_state_refresh(self):
        pass
