"""Export one publishable before/after example per stratum.

    python -m rdfeval article

Design record ``corpus/403`` asks each stratum to produce **at least one**
before/after pair publishable in the article: the rdflib extract as found and
its translation, with provenance (repository, file, commit) and the licence
that allows reproducing it.

Candidates are taken from **approved** pairs only — a draft an agent produced
is a hypothesis, not something to print — and among those, preference goes to
the pair the translators flagged ``article_candidate``, then to the one whose
notation gain is clearest per line of extract.  A stratum with no candidate
yet is named, not skipped: the gap is part of the report.

Output: ``results/article_examples/<stratum>.md``, regenerable.
"""

from __future__ import annotations

import json

from .config import RESULTS_SUMMARY
from .study import Study, STUDY
from .surface import STRATA
from .validate import iter_examples

ARTICLE_DIR = RESULTS_SUMMARY.parent / "article_examples"

TEMPLATE = """\
<!-- Generated by `rdfeval article`. Do not edit: edit the pair instead. -->
# {stratum} — {description}

Source: [`{repository}`](https://github.com/{repository}) at `{commit}`,
file `{path}`, region `{qualname}` (lines {lineno}–{end_lineno}).
Licence: {licence}. Oracle: {oracle}. Classification: {classification}.

Constructions employed: {constructions}

## Before — rdflib

```python
{python}
```

## After — linked-data-python

```ldpy
{ldpy}
```

{notes}
"""


def _licence_of(repository: str) -> str:
    from .select import load_manifest
    for rec in load_manifest():
        if rec["full_name"] == repository:
            return rec.get("licence") or rec.get("license") or "unknown"
    return "unknown"


def _strip_header(text: str) -> str:
    """Drop the provenance comment block: the page states it in prose."""
    lines = text.splitlines()
    while lines and lines[0].startswith("#"):
        lines.pop(0)
    while lines and not lines[0].strip():
        lines.pop(0)
    return "\n".join(lines)


def candidates(study: Study) -> dict[str, list[tuple]]:
    """Approved pairs, grouped by every stratum they are credited to."""
    out: dict[str, list[tuple]] = {k: [] for k in STRATA}
    for ex_dir, meta in iter_examples(study):
        review = ex_dir / "review.json"
        if not review.exists():
            continue
        try:
            if json.loads(review.read_text()).get("review_status") != "approved":
                continue
        except (OSError, ValueError):
            continue
        if meta.get("classification") in ("not-expressible", "excluded"):
            continue
        for stratum in meta.get("strata", []) or [meta.get(study.group)]:
            if stratum in out:
                out[stratum].append((ex_dir, meta))
    return out


def _rank(item) -> tuple:
    ex_dir, meta = item
    flagged = 0 if meta.get("article_candidate") else 1
    loc = len((ex_dir / "original.py").read_text().splitlines())
    return (flagged, abs(loc - 25), meta["region_id"])


def run(config: dict, study: Study = STUDY) -> None:
    pools = candidates(study)
    ARTICLE_DIR.mkdir(parents=True, exist_ok=True)
    written, missing = [], []
    for stratum, pool in pools.items():
        if not pool:
            missing.append(stratum)
            continue
        ex_dir, meta = sorted(pool, key=_rank)[0]
        notes = meta.get("translation_notes") or []
        page = TEMPLATE.format(
            stratum=stratum,
            description=STRATA[stratum],
            repository=meta["repository"],
            commit=meta["commit"],
            path=meta["path"],
            qualname=meta["qualname"],
            lineno=meta["lineno"], end_lineno=meta["end_lineno"],
            licence=_licence_of(meta["repository"]),
            oracle=meta.get("oracle", "isomorphism"),
            classification=meta.get("classification") or "unclassified",
            constructions=", ".join(f"`{c}`" for c in
                                    meta.get("constructions", [])) or "—",
            python=_strip_header((ex_dir / "original.py").read_text()),
            ldpy=_strip_header((ex_dir / "translated.ldpy").read_text()),
            notes=("\n".join(f"> {n}" for n in notes) + "\n") if notes else "",
        )
        path = ARTICLE_DIR / f"{stratum}.md"
        path.write_text(page, encoding="utf-8")
        written.append((stratum, meta["region_id"], len(pool)))
    for stratum, rid, n in written:
        print(f"  {stratum:24s} {rid}  (chosen from {n} approved)")
    print(f"article: {len(written)} strata exported to {ARTICLE_DIR}")
    if missing:
        print(f"  ! no approved pair yet for: {', '.join(missing)}")
    # provenance does not wait for review: it says where each construction was
    # found, and cites rather than reproduces
    write_constructions_table(study)


# --------------------------------------------------------------------------
# Provenance table: every construction, and where it was actually found
# --------------------------------------------------------------------------

CONSTRUCTIONS_TEX = RESULTS_SUMMARY / "constructions.tex"

_TEX_ESCAPE = {"&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
               "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}",
               "^": r"\textasciicircum{}", "\\": r"\textbackslash{}"}


def _tex(text: str) -> str:
    return "".join(_TEX_ESCAPE.get(c, c) for c in str(text))


def _cite(meta) -> str:
    """`repository`, `path`:line — the evidence that the construction was
    found, not invented."""
    # the path is long and must be allowed to wrap: \\path does not break,
    # so the slashes carry explicit break opportunities
    path = (_tex(meta["path"]).replace("/", "/\\allowbreak{}")
            .replace("-", "-\\allowbreak{}"))
    return "\\texttt{\\scriptsize %s}, \\texttt{\\scriptsize %s}:%d" % (
        (_tex(meta["repository"]).replace("/", "/\\allowbreak{}")
         .replace("-", "-\\allowbreak{}")),
        path, meta["lineno"])


def constructions_table(study: Study = STUDY) -> str:
    """One row per construction: how many regions use it, and one of them.

    This table answers a question the aggregates cannot: was each construct
    of the language reached by code somebody had already written?  It is
    therefore built from every TRANSLATED region, not from the approved
    subset — it reports provenance, not a measurement, and cites without
    reproducing, so the licence of the repository does not gate it.
    """
    from .constructions import normalise

    seen: dict[str, list] = {}
    for ex_dir, meta in iter_examples(study):
        if meta.get("translation_status") != "final":
            continue
        named, _ = normalise(meta.get("constructions") or [])
        for name in named:
            seen.setdefault(name, []).append(meta)

    def _pick(metas):
        # the region that declares the FEWEST constructions is the one whose
        # citation points most squarely at this one
        return sorted(metas, key=lambda m: (len(m.get("constructions") or []),
                                            m["region_id"]))[0]

    rows = sorted(seen.items(), key=lambda kv: (-len(kv[1]), kv[0]))
    out = [
        "% Generated by `rdfeval article`. Do not edit.",
        r"\begin{tabular}{@{}llr >{\raggedright\arraybackslash}p{0.36\linewidth}@{}}",
        r"\toprule",
        r"construction & stratum & $n$ & found in \\",
        r"\midrule",
    ]
    for name, metas in rows:
        m = _pick(metas)
        out.append("\\texttt{%s} & \\texttt{%s} & %d & %s \\\\"
                   % (_tex(name), _tex(m.get("stratum", "—")),
                      len(metas), _cite(m)))
    out += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(out) + "\n"


def write_constructions_table(study: Study = STUDY) -> int:
    CONSTRUCTIONS_TEX.parent.mkdir(parents=True, exist_ok=True)
    text = constructions_table(study)
    CONSTRUCTIONS_TEX.write_text(text, encoding="utf-8")
    n = text.count("\\\\") - 1          # header row
    print(f"article: {n} constructions with provenance -> {CONSTRUCTIONS_TEX}")
    return n
