# Context shim (see meta.json): subset of blobfish/pyrdf/_AORC.py,
# blobfish/aorc/parse_transfer.py (GraphCreator, NodeNamer, AORCFilter) and
# blobfish/aorc/transfer.py (the metadata dataclass), from
# Dewberry/blobfish@db89f3422899a52cd7ee23d9fa4c85f396db7e7f, so the region
# executes outside its package.  Identical bindings for both representations.
#
# AORC is the real project namespace IRI from _AORC.py's DefinedNamespace,
# reduced to a plain rdflib Namespace (attribute access only, no validation).
#
# CompletedTransferMetadata is trimmed to a plain field container: the real
# dataclass derives mirror_uri/mirror_public_uri/ref_end_date/rfc_office_uri
# in __post_init__ from the other fields, and rfc_office_uri's derivation
# (__validate_rfc_office_page) makes a live HTTP request. The region under
# study (create_graph_triples) only ever *reads* the already-derived fields
# off `meta` -- it never constructs a CompletedTransferMetadata itself -- so
# the driver supplies already-derived values directly, like any other
# fixture. No derivation logic is invented; the network call is simply not
# reproduced.
import logging
import enum
from dataclasses import dataclass

from rdflib import Namespace

AORC = Namespace("https://github.com/Dewberry/blobfish/blob/aorc_refactor/semantics/rdf/aorc.ttl#")

# ldpy's prefix-import protocol (`from context_shim import aorc:`, see
# reference/language/declarations.md "Prefixes across modules") reads this
# dict off the imported module -- normally auto-generated by the transpiler
# for an .ldpy module that declares `@prefix aorc: <...> .` at module level;
# this is a plain .py shim, so it is provided by hand, to the same shape.
__namespaces__ = {"aorc": AORC}


class AORCFilter(enum.Enum):
    YEAR = enum.auto()
    RFC = enum.auto()


class GraphCreator:
    """Verbatim except serialize_graphs (not reached by the region, and it
    pulls in S3 upload helpers this shim has no reason to carry)."""

    def __init__(self, bindings: dict) -> None:
        self.bindings = bindings
        self.filter_graphs = dict()
        self.default_graph = None

    def __create_graph(self):
        from rdflib import Graph
        logging.info("rdflib.Graph object created by graph creator")
        g = Graph()
        for prefix, ns in self.bindings.items():
            g.bind(prefix, ns)
        return g

    def get_graph(self, filter_key: str | None = None):
        if filter_key:
            filter_graph = self.filter_graphs.get(filter_key)
            if filter_graph:
                return filter_graph
            logging.info(f"No graph found for filter key {filter_key}")
            filter_graph = self.__create_graph()
            self.filter_graphs[filter_key] = filter_graph
            return filter_graph
        if self.default_graph:
            return self.default_graph
        self.default_graph = self.__create_graph()
        return self.default_graph


class NodeNamer:
    """Verbatim."""

    def __init__(self) -> None:
        self.name_set = set()

    def __verify_name(self, new_name: str) -> None:
        if new_name in self.name_set:
            logging.error("Duplicate name already exists: {0}".format(new_name))
            raise ValueError
        self.name_set.add(new_name)

    def name_source_ds(self, meta) -> str:
        fn_index = meta.source_uri.rfind("/") + 1
        fn = meta.source_uri[fn_index:].replace(".zip", "")
        self.__verify_name(fn)
        return fn

    def name_ds_period(self, meta) -> str:
        return f"{meta.ref_date}_{meta.ref_end_date}"

    def name_transfer(self, meta):
        fn_index = meta.source_uri.rfind("/") + 1
        fn = meta.source_uri[fn_index:].replace(".zip", "")
        return f"{meta.mirror_script}_{fn}"


@dataclass
class CompletedTransferMetadata:
    """Plain field container -- see module docstring above for what is
    deliberately not reproduced (the __post_init__ derivations)."""

    rfc_name: str
    rfc_alias: str
    rfc_catalog_uri: str
    precip_partition_uri: str
    source_uri: str
    mirror_uri: str
    ref_date: str
    docker_image_url: str
    mirror_script: str
    aorc_historic_uri: str
    source_last_modified: str
    source_bytes: str
    mirror_last_modified: str
    bucket: str
    mirror_public_uri: str
    ref_end_date: str
    rfc_office_uri: str
