# Extracted from lync-cyber/CataForge@8cdf9be0d3 : scripts/codegen_kg_schema.py
# region: _canonicalize_shacl (lines 147-196, stratum ns_def_local)
# licence of the source repository: see meta.json
from typing import Any

def _canonicalize_shacl(turtle_text: str) -> str:
    """Byte-stable form of ShaclGenerator output.

    ShaclGenerator is nondeterministic in two validation-irrelevant ways:
    property-shape emission order (blank-node structure) and the element order
    of set-semantics RDF lists (`sh:ignoredProperties`, `sh:in`). It also
    assigns `sh:order` (a SHACL *non-validating* presentation property) from
    that unstable iteration order. Canonical form: drop `sh:order`, sort the
    set-lists, relabel blank nodes canonically, emit sorted N-Triples (a
    Turtle subset, so downstream `format="turtle"` parsers are unaffected).

    Blank-node relabeling uses the forest fast path (`_blank_node_labels`);
    if the graph is not a forest it falls back to rdflib's general
    `to_canonical_graph`, which is correct but O(n) graph-isomorphism work.
    """
    import rdflib
    from rdflib.collection import Collection

    sh = rdflib.Namespace("http://www.w3.org/ns/shacl#")
    graph = rdflib.Graph()
    graph.parse(data=turtle_text, format="turtle")
    graph.remove((None, sh.order, None))
    for pred in (sh.ignoredProperties, sh["in"]):
        for subject, head in list(graph.subject_objects(pred)):
            items = list(Collection(graph, head))
            Collection(graph, head).clear()  # type: ignore[no-untyped-call]
            graph.remove((subject, pred, head))
            new_head = rdflib.BNode()
            Collection(graph, new_head, sorted(items, key=str))
            graph.add((subject, pred, new_head))

    labels = _blank_node_labels(graph)
    if labels is None:
        from rdflib.compare import to_canonical_graph

        emit = to_canonical_graph(graph)
        lines = sorted(line for line in emit.serialize(format="nt").splitlines() if line)
    else:

        def term(node: Any) -> str:
            label = labels[node] if isinstance(node, rdflib.BNode) else node
            return str(label.n3())

        lines = sorted(f"{term(s)} {p.n3()} {term(o)} ." for s, p, o in graph)
    header = [
        "# Auto-generated by scripts/codegen_kg_schema.py — do not edit.",
        "# Canonicalized SHACL shapes (sorted N-Triples; sh:order stripped,",
        "# set-semantics lists sorted) so regeneration is byte-stable.",
    ]
    return "\n".join(header + lines) + "\n"
