# Context shim (see meta.json): the vocabulary namespaces from
# fdpneo_server/shared/namespaces.py, the path constant from
# fdpneo_server/shared/reserved.py, and the two triple-producing helpers
# (direct_container_config, _service_advertisement) from
# fdpneo_server/metadata/profiles/applier.py -- the same file as the region,
# just outside its line range (451-486) -- from
# FAIRDataTeam/fdpneo-server@3e72e119aeaf8617dd94060b5ff1a09097f20b82,
# copied verbatim so the region executes outside its package. Identical
# bindings for both representations.
from rdflib import BNode, Literal, Namespace, URIRef
from rdflib.namespace import RDF

DCAT = Namespace("http://www.w3.org/ns/dcat#")
DCT = Namespace("http://purl.org/dc/terms/")
LDP = Namespace("http://www.w3.org/ns/ldp#")
ODRL = Namespace("http://www.w3.org/ns/odrl/2/")
VOID = Namespace("http://rdfs.org/ns/void#")

# ldpy's prefix-import protocol (`from context_shim import dct:`, see
# reference/language/declarations.md "Prefixes across modules") reads this
# dict off the imported module -- normally auto-generated by the transpiler
# for an .ldpy module that declares `@prefix dct: <...> .` at module level;
# this is a plain .py shim, so it is provided by hand, to the same shape.
# Only DCT is exported as a prefix: it is the only one of the five region
# namespaces used as a literal vocabulary term inside the region itself
# (DCAT/LDP/ODRL/VOID are used by the two helpers below, not by the region).
__namespaces__ = {"dct": DCT}

RESERVED_API_PATH = "/fdp-api"


def direct_container_config(
    subject: URIRef, member_relations: list[str]
) -> list[tuple[URIRef, URIRef, URIRef]]:
    """LDP Direct Container membership triples for a container ``subject``."""
    triples: list[tuple[URIRef, URIRef, URIRef]] = [
        (subject, RDF.type, LDP.DirectContainer),
        (subject, LDP.membershipResource, subject),
        (subject, LDP.insertedContentRelation, LDP.MemberSubject),
    ]
    triples += [(subject, LDP.hasMemberRelation, URIRef(rel)) for rel in member_relations]
    return triples


def _service_advertisement(
    subject: URIRef, base_iri: str, *, search_enabled: bool
) -> list[tuple[URIRef | BNode, URIRef, URIRef | Literal | BNode]]:
    """Triples advertising this FDP's SPARQL/search endpoints on the root record."""
    base = base_iri.rstrip("/")
    sparql_url = f"{base}{RESERVED_API_PATH}/sparql"
    triples: list[tuple[URIRef | BNode, URIRef, URIRef | Literal | BNode]] = [
        (subject, VOID.sparqlEndpoint, URIRef(sparql_url)),
    ]
    sparql_svc = BNode()
    triples += [
        (subject, DCAT.service, sparql_svc),
        (sparql_svc, RDF.type, DCAT.DataService),
        (sparql_svc, DCT.title, Literal("SPARQL query endpoint")),
        (sparql_svc, DCAT.endpointURL, URIRef(sparql_url)),
        (sparql_svc, DCAT.endpointDescription, URIRef("https://www.w3.org/TR/sparql11-protocol/")),
        (sparql_svc, DCAT.servesDataset, subject),
    ]
    if search_enabled:
        search_svc = BNode()
        triples += [
            (subject, DCAT.service, search_svc),
            (search_svc, RDF.type, DCAT.DataService),
            (search_svc, DCT.title, Literal("Metadata search API")),
            (search_svc, DCAT.endpointURL, URIRef(f"{base}{RESERVED_API_PATH}/search")),
            (search_svc, DCAT.servesDataset, subject),
        ]
    return triples
