"""Validation driver for BrickSchema__Brick__handle_extensions.py__<module>_1.

The region is a whole script: it parses "Brick.ttl" and every "extensions/*.ttl"
from the current directory, rewrites the graph, and writes
"Brick+extensions.ttl".  Brick.ttl is generated by generate_brick.py and is not
in the repository, so the driver stages a working directory from the fixtures
next to this file and runs both versions there — identical inputs, identical
file names, and nothing written back into the example directory.

Oracle: module state — the `brick_graph` global of both runs, by RDF
isomorphism (meta.oracle == "isomorphism").
"""
import os
import shutil
import tempfile
from pathlib import Path

from rdfeval.harness import run_pair

HERE = Path(__file__).resolve().parent

work = Path(tempfile.mkdtemp(prefix="brick-handle-extensions-"))
shutil.copy(HERE / "fixture.ttl", work / "Brick.ttl")
shutil.copytree(HERE / "extensions_fixture", work / "extensions")
os.chdir(work)

VERDICT = run_pair(str(HERE / "driver.py"), entry=None, calls=None)

os.chdir(HERE)
shutil.rmtree(work, ignore_errors=True)
