# Context shim (see meta.json): the vocabulary namespaces from
# fdpneo_server/shared/namespaces.py, the graph-URI helper from
# fdpneo_server/shared/graphs.py (re-exported by fdpneo_server/metadata/
# graphs.py), the state type from fdpneo_server/metadata/states.py, and the
# Operation/MetaResult types plus the private `_next_version` /
# `_extract_creation` / `_extract_state` / `_extract_validated_against`
# helpers from fdpneo_server/metadata/meta.py itself (the same file as the
# region, just outside its line range 78-161) -- from
# FAIRDataTeam/fdpneo-server@3e72e119aeaf8617dd94060b5ff1a09097f20b82,
# copied verbatim so the region executes outside its package. Identical
# bindings for both representations.
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import StrEnum

from rdflib import Graph, Literal, Namespace, URIRef

DCT = Namespace("http://purl.org/dc/terms/")
OWL = Namespace("http://www.w3.org/2002/07/owl#")
PROV = Namespace("http://www.w3.org/ns/prov#")
FDP_DEFAULT = Namespace("https://w3id.org/fdp/o#")
FDP_VALIDATED_AGAINST = FDP_DEFAULT["validatedAgainst"]
FDP_METADATA_STATE = FDP_DEFAULT["metadataState"]
FDP_CREATE_OPERATION = FDP_DEFAULT["CreateOperation"]
FDP_MODIFY_OPERATION = FDP_DEFAULT["ModifyOperation"]

# ldpy's prefix-import protocol (`from context_shim import dct:`, see
# reference/language/declarations.md "Prefixes across modules") reads this
# dict off the imported module -- normally auto-generated by the transpiler
# for an .ldpy module that declares `@prefix dct: <...> .` at module level;
# this is a plain .py shim, so it is provided by hand, to the same shape.
# Only the three namespaces the region itself uses as literal vocabulary
# terms are exported as prefixes -- "fdp-o" is the project's own binding for
# FDP_DEFAULT (see PREFIXES in the real shared/namespaces.py).
__namespaces__ = {"dct": DCT, "owl": OWL, "prov": PROV, "fdp-o": FDP_DEFAULT}


class MetadataState(StrEnum):
    """A record's publication state."""

    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    ARCHIVED = "ARCHIVED"


DEFAULT_STATE = MetadataState.DRAFT


class Operation(StrEnum):
    """The operation a meta graph refresh records."""

    CREATE = "create"
    MODIFY = "modify"


@dataclass(frozen=True)
class MetaResult:
    """Output of build_meta_graph."""

    graph: Graph
    operation: Operation
    version: int
    state: MetadataState


def _stripped(record_uri: str | URIRef) -> str:
    return str(record_uri).rstrip("/")


def record_graph_uri(record_uri: str | URIRef) -> URIRef:
    return URIRef(_stripped(record_uri))


def meta_graph_uri(record_uri: str | URIRef) -> URIRef:
    return URIRef(_stripped(record_uri) + "/meta")


def _next_version(prior: Graph, record_subject: URIRef) -> int:
    for value in prior.objects(record_subject, OWL.versionInfo):
        if isinstance(value, Literal):
            try:
                return int(str(value)) + 1
            except ValueError:
                return 1
    return 1


def _extract_creation(
    prior: Graph,
    record_subject: URIRef,
) -> tuple[datetime | None, str | None]:
    created: datetime | None = None
    for value in prior.objects(record_subject, DCT.created):
        if isinstance(value, Literal):
            raw = value.toPython()
            if isinstance(raw, datetime):
                created = raw
            else:
                try:
                    created = datetime.fromisoformat(str(value))
                except ValueError:
                    created = None
        break
    creator: str | None = None
    for value in prior.objects(record_subject, DCT.creator):
        if isinstance(value, URIRef):
            creator = str(value)
            break
    return created, creator


def _extract_validated_against(prior: Graph, record_subject: URIRef) -> str | None:
    """Return the profile version IRI the record was last validated against."""
    for value in prior.objects(record_subject, FDP_VALIDATED_AGAINST):
        if isinstance(value, URIRef):
            return str(value)
    return None


def _extract_state(prior: Graph, record_subject: URIRef) -> MetadataState | None:
    """Return the prior publication state, or None if not present/invalid."""
    for value in prior.objects(record_subject, FDP_METADATA_STATE):
        try:
            return MetadataState(str(value))
        except ValueError:
            return None
    return None
