# Context shim (see meta.json): the DCT vocabulary namespace from
# fdpneo_server/shared/namespaces.py, FAIRDataTeam/fdpneo-server@
# 3e72e119aeaf8617dd94060b5ff1a09097f20b82, so the region executes outside
# the package (`fdpneo_server` is not installed: `import fdpneo_server` ->
# ModuleNotFoundError, checked directly). FDP_METADATA_STATE and SH are
# imported by the original module-level statement but never referenced
# inside this region's six lines, so they are not reproduced here (adding
# invented values for names the region never reads would not make it any
# more faithful). Identical bindings for both representations.
from rdflib import Namespace

DCT = Namespace("http://purl.org/dc/terms/")

# ldpy's prefix-import protocol (`from context_shim import dct:`, see
# reference/language/declarations.md "Prefixes across modules") reads this
# dict off the imported module -- normally auto-generated by the transpiler
# for an .ldpy module that declares `@prefix dct: <...> .` at module level;
# this is a plain .py shim, so it is provided by hand, to the same shape.
__namespaces__ = {"dct": DCT}
